version: "3.1"
# This is just an example that shows the relationships between the groups image
# and other services. Many of these things would be overidden in the actual
# deployment docker-compose file - for example, the name of the mongodb instance
# that is started up and polled
services:
  kbase_groups:
    build: .
    ports:
      - "8080:8080"
    environment:
      mongo_host: "mongo:27017"
      mongo_db: dc_groups_test
      auth_url: https://ci.kbase.us/services/auth
      workspace_url: https://ci.kbase.us/services/ws
      catalog_url: https://ci.kbase.us/services/catalog
      notifier_url: https://ci.kbase.us/services/feeds
      workspace_admin_token: faketoken_replace
      notifier_token: faketoken_replace
      field_validator_configs: |
         field-foo-validator=us.kbase.groups.fieldvalidators.SimpleFieldValidatorFactory
         field-foo-is-numbered=true
      # add more configurations here
    command:
      - "-multiline"
      - "-wait"
      - "tcp://mongo:27017"
      - "-timeout"
      - "120s"
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "java"
      - "-Djetty.home=/usr/local/jetty"
      - "-jar"
      - "/usr/local/jetty/start.jar"
    depends_on: ["mongo"]

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"

